// App/src/pages/Login.jsx
import { useState, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { GraduationCap, Lock, User } from 'lucide-react'

export default function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const { login, user } = useAuth()
  const navigate = useNavigate()

  // Redirect if already logged in
  useEffect(() => {
    if (user) {
      switch (user.role_name) {
        case 'Admin':
          navigate('/admin/dashboard', { replace: true })
          break
        case 'Mahasiswa':
          navigate('/student/dashboard', { replace: true })
          break
        case 'Dosen Wali':
          navigate('/lecturer/dashboard', { replace: true })
          break
        default:
          break
      }
    }
  }, [user, navigate])

  const handleSubmit = async (e) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    try {
      const result = await login(username, password)
      if (result.success) {
        // Navigation will be handled by useEffect above
      } else {
        setError(result.message || 'Login failed. Please check your credentials.')
      }
    } catch (err) {
      setError('An error occurred. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 to-primary-100 px-4">
      <div className="max-w-md w-full">
        <div className="text-center mb-8">
          <div className="flex justify-center mb-4">
            <div className="bg-primary-600 p-3 rounded-full">
              <GraduationCap className="w-12 h-12 text-white" />
            </div>
          </div>
          <h1 className="text-3xl font-bold text-gray-900">Student Achievement System</h1>
          <p className="mt-2 text-gray-600">Sign in to your account</p>
        </div>

        <div className="card">
          <form onSubmit={handleSubmit} className="space-y-6">
            {error && (
              <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
                <p className="text-sm text-red-600">{error}</p>
              </div>
            )}

            <div>
              <label htmlFor="username" className="block text-sm font-medium text-gray-700 mb-2">
                Username
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <User className="h-5 w-5 text-gray-400" />
                </div>
                <input
                  id="username"
                  type="text"
                  required
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="input pl-10"
                  placeholder="Enter your username"
                />
              </div>
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-2">
                Password
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <Lock className="h-5 w-5 text-gray-400" />
                </div>
                <input
                  id="password"
                  type="password"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="input pl-10"
                  placeholder="Enter your password"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="btn btn-primary w-full"
            >
              {loading ? 'Signing in...' : 'Sign In'}
            </button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-sm text-gray-600">
              Don't have an account?{' '}
              <Link to="/register" className="font-medium text-primary-600 hover:text-primary-500">
                Register here
              </Link>
            </p>
          </div>

          <div className="mt-6 p-4 bg-blue-50 rounded-lg">
            <p className="text-sm font-medium text-gray-700 mb-2">Demo Accounts:</p>
            <div className="space-y-1 text-xs text-gray-600">
              <p><strong>Admin:</strong> admin / admin123</p>
              <p><strong>Student:</strong> student001 / student123</p>
              <p><strong>Lecturer:</strong> lecturer001 / lecturer123</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { api } from '$lib/api';
	import { authStore } from '$lib/stores/auth';
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';

	let isLogin = $state(true);
	let loading = $state(false);
	let error = $state('');

	// Login form
	let loginUsername = $state('');
	let loginPassword = $state('');

	// Register form
	let regUsername = $state('');
	let regEmail = $state('');
	let regFullName = $state('');
	let regPassword = $state('');
	let regRole = $state('Mahasiswa');

	let isAuthenticated = $derived($authStore.isAuthenticated);

	onMount(() => {
		if (isAuthenticated) {
			goto('/dashboard');
		}
	});

	async function handleLogin(e: Event) {
		e.preventDefault();
		loading = true;
		error = '';

		try {
			const result = await api.login(loginUsername, loginPassword);
			
			if (result.status === 'success' && result.data) {
				authStore.login(result.data.token, result.data.user);
				goto('/dashboard');
			} else {
				error = result.message || 'Login failed';
			}
		} catch (err) {
			error = 'Network error. Please try again.';
		} finally {
			loading = false;
		}
	}

	async function handleRegister(e: Event) {
		e.preventDefault();
		loading = true;
		error = '';

		try {
			const result = await api.register({
				username: regUsername,
				email: regEmail,
				fullName: regFullName,
				password: regPassword,
				roleName: regRole
			});

			if (result.status === 'success') {
				alert('Registration successful! Please login.');
				isLogin = true;
				// Reset form
				regUsername = '';
				regEmail = '';
				regFullName = '';
				regPassword = '';
				regRole = 'Mahasiswa';
			} else {
				error = result.message || 'Registration failed';
			}
		} catch (err) {
			error = 'Network error. Please try again.';
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center px-4 bg-gradient-to-br from-primary-50 to-primary-100">
	<div class="card max-w-md w-full p-8 shadow-xl">
		<div class="text-center mb-8">
			<div class="w-16 h-16 bg-gradient-to-br from-primary-500 to-primary-600 rounded-full flex items-center justify-center mx-auto mb-4">
				<svg class="w-10 h-10 text-white" fill="currentColor" viewBox="0 0 20 20">
					<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
				</svg>
			</div>
			<h1 class="text-3xl font-bold text-gray-800">Achievement System</h1>
			<p class="text-gray-600 mt-2">Manage your academic achievements</p>
		</div>

		<!-- Tab Switcher -->
		<div class="flex border-b border-gray-200 mb-6">
			<button
				class="flex-1 py-2 text-center font-medium transition {isLogin ? 'border-b-2 border-primary-500 text-primary-600' : 'text-gray-500'}"
				onclick={() => { isLogin = true; error = ''; }}
			>
				Login
			</button>
			<button
				class="flex-1 py-2 text-center font-medium transition {!isLogin ? 'border-b-2 border-primary-500 text-primary-600' : 'text-gray-500'}"
				onclick={() => { isLogin = false; error = ''; }}
			>
				Register
			</button>
		</div>

		{#if error}
			<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
				{error}
			</div>
		{/if}

		{#if isLogin}
			<!-- Login Form -->
			<form onsubmit={handleLogin} class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Username</label>
					<input
						type="text"
						bind:value={loginUsername}
						required
						class="input"
						placeholder="Enter username"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Password</label>
					<input
						type="password"
						bind:value={loginPassword}
						required
						class="input"
						placeholder="Enter password"
					/>
				</div>
				<button
					type="submit"
					disabled={loading}
					class="w-full btn btn-primary"
				>
					{loading ? 'Loading...' : 'Login'}
				</button>
			</form>
		{:else}
			<!-- Register Form -->
			<form onsubmit={handleRegister} class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Username</label>
					<input
						type="text"
						bind:value={regUsername}
						required
						class="input"
						placeholder="Choose username"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
					<input
						type="email"
						bind:value={regEmail}
						required
						class="input"
						placeholder="your.email@example.com"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Full Name</label>
					<input
						type="text"
						bind:value={regFullName}
						required
						class="input"
						placeholder="Your full name"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Password</label>
					<input
						type="password"
						bind:value={regPassword}
						required
						class="input"
						placeholder="Choose password"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-1">Role</label>
					<select bind:value={regRole} class="input">
						<option value="Mahasiswa">Mahasiswa</option>
						<option value="Dosen Wali">Dosen Wali</option>
						<option value="Admin">Admin</option>
					</select>
				</div>
				<button
					type="submit"
					disabled={loading}
					class="w-full btn btn-primary"
				>
					{loading ? 'Loading...' : 'Register'}
				</button>
			</form>
		{/if}
	</div>
</div>
